version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alpha
  coins:
  - 10000token
  - 100000000stake
- name: bravo
  coins:
  - 20000token
  - 200000000stake
- name: charlie
  coins:
  - 30000token
  - 300000000stake
- name: delta
  coins:
  - 40000token
  - 400000000stake
faucet:
  name: bravo
  coins:
  - 5token
  - 200000stake
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alpha
  bonded: 100000000stake
