version: 1
accounts:
  - name: alpha
    coins: ["20000token", "200000000stake"]
  - name: bravo
    coins: ["10000token", "100000000stake"]
validators:
  - name: alpha
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bravo
  coins: ["5token", "100000stake"]
