// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carauction/carauction/end_auction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EndAuction struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id          uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	AuctionID   uint64 `protobuf:"varint,3,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	BidID       uint64 `protobuf:"varint,4,opt,name=bidID,proto3" json:"bidID,omitempty"`
	HammerPrice string `protobuf:"bytes,5,opt,name=hammerPrice,proto3" json:"hammerPrice,omitempty"`
	Winner      string `protobuf:"bytes,6,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (m *EndAuction) Reset()         { *m = EndAuction{} }
func (m *EndAuction) String() string { return proto.CompactTextString(m) }
func (*EndAuction) ProtoMessage()    {}
func (*EndAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f1a5cf8421b0245, []int{0}
}
func (m *EndAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EndAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EndAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EndAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndAuction.Merge(m, src)
}
func (m *EndAuction) XXX_Size() int {
	return m.Size()
}
func (m *EndAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_EndAuction.DiscardUnknown(m)
}

var xxx_messageInfo_EndAuction proto.InternalMessageInfo

func (m *EndAuction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EndAuction) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EndAuction) GetAuctionID() uint64 {
	if m != nil {
		return m.AuctionID
	}
	return 0
}

func (m *EndAuction) GetBidID() uint64 {
	if m != nil {
		return m.BidID
	}
	return 0
}

func (m *EndAuction) GetHammerPrice() string {
	if m != nil {
		return m.HammerPrice
	}
	return ""
}

func (m *EndAuction) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

func init() {
	proto.RegisterType((*EndAuction)(nil), "auction.auction.EndAuction")
}

func init() {
	proto.RegisterFile("carauction/carauction/end_auction.proto", fileDescriptor_2f1a5cf8421b0245)
}

var fileDescriptor_2f1a5cf8421b0245 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x4e, 0x2c, 0x4a,
	0x2c, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x47, 0x62, 0xa6, 0xe6, 0xa5, 0xc4, 0x43, 0xd9, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xfc, 0x30, 0x2e, 0x94, 0x56, 0x5a, 0xc2, 0xc8, 0xc5, 0xe5,
	0x9a, 0x97, 0xe2, 0x08, 0xe1, 0x0a, 0x49, 0x70, 0xb1, 0x27, 0x17, 0xa5, 0x26, 0x96, 0xe4, 0x17,
	0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x32, 0x5c, 0x9c, 0x50, 0x33, 0x3c,
	0x5d, 0x24, 0x98, 0xc1, 0xc2, 0x08, 0x01, 0x21, 0x11, 0x2e, 0xd6, 0xa4, 0xcc, 0x14, 0x4f, 0x17,
	0x09, 0x16, 0xb0, 0x0c, 0x84, 0x23, 0xa4, 0xc0, 0xc5, 0x9d, 0x91, 0x98, 0x9b, 0x9b, 0x5a, 0x14,
	0x50, 0x94, 0x99, 0x9c, 0x2a, 0xc1, 0x0a, 0xb6, 0x01, 0x59, 0x48, 0x48, 0x8c, 0x8b, 0xad, 0x3c,
	0x33, 0x2f, 0x2f, 0xb5, 0x48, 0x82, 0x0d, 0x2c, 0x09, 0xe5, 0x39, 0x59, 0x9c, 0x78, 0x24, 0xc7,
	0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c,
	0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x5c, 0x72, 0x62, 0x91, 0x2e, 0xcc, 0xc3, 0x15, 0xc8,
	0xbe, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0x7b, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x81, 0xdb, 0xd0, 0x51, 0x23, 0x01, 0x00, 0x00,
}

func (m *EndAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EndAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Winner) > 0 {
		i -= len(m.Winner)
		copy(dAtA[i:], m.Winner)
		i = encodeVarintEndAuction(dAtA, i, uint64(len(m.Winner)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.HammerPrice) > 0 {
		i -= len(m.HammerPrice)
		copy(dAtA[i:], m.HammerPrice)
		i = encodeVarintEndAuction(dAtA, i, uint64(len(m.HammerPrice)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BidID != 0 {
		i = encodeVarintEndAuction(dAtA, i, uint64(m.BidID))
		i--
		dAtA[i] = 0x20
	}
	if m.AuctionID != 0 {
		i = encodeVarintEndAuction(dAtA, i, uint64(m.AuctionID))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintEndAuction(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEndAuction(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEndAuction(dAtA []byte, offset int, v uint64) int {
	offset -= sovEndAuction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EndAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEndAuction(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovEndAuction(uint64(m.Id))
	}
	if m.AuctionID != 0 {
		n += 1 + sovEndAuction(uint64(m.AuctionID))
	}
	if m.BidID != 0 {
		n += 1 + sovEndAuction(uint64(m.BidID))
	}
	l = len(m.HammerPrice)
	if l > 0 {
		n += 1 + l + sovEndAuction(uint64(l))
	}
	l = len(m.Winner)
	if l > 0 {
		n += 1 + l + sovEndAuction(uint64(l))
	}
	return n
}

func sovEndAuction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEndAuction(x uint64) (n int) {
	return sovEndAuction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EndAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndAuction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEndAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionID", wireType)
			}
			m.AuctionID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidID", wireType)
			}
			m.BidID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HammerPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEndAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HammerPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEndAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndAuction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEndAuction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEndAuction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEndAuction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEndAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEndAuction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEndAuction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEndAuction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEndAuction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEndAuction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEndAuction = fmt.Errorf("proto: unexpected end of group")
)
